---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/"
)
```

# wbstats: An R package for searching and downloading data from the World Bank API.

You can install:

The latest release version from CRAN with
```{r, eval = FALSE}
install.packages("wbstats")
```

or

The latest development version from github with
```{r, eval = FALSE}
remotes::install_github("nset-ornl/wbstats")
```

# Downloading data from the World Bank

```{r readme-download, warning=FALSE}
library(wbstats)

# Population for every country from 1960 until present
d <- wb(country = "all", "SP.POP.TOTL")
    
head(d)
```


## Hans Rosling's Gapminder using `wbstats`

```{r readme-chart, warning=FALSE, message=FALSE, fig.width=12, fig.height=6}
library(tidyverse)
library(wbstats)

my_indicators <- c(
  "SP.DYN.LE00.IN", # Life Expectancy
  "NY.GDP.PCAP.CD", # GDP
  "SP.POP.TOTL" # Total Population
  )

## Extracting the data from world bank, using the restful api via the wb()
d <- wb(country = "all", my_indicators, startdate = 2016, enddate = 2016)

## data cleaning and rearranging
d <- d %>% 
  select(-indicator) %>% 
  spread(indicatorID, value) %>% 
  rename(life_exp = SP.DYN.LE00.IN, gdp_capita = NY.GDP.PCAP.CD, pop = SP.POP.TOTL) %>% 
  left_join(wbcountries(), "iso3c")


## Data visualization
d %>%
  ggplot() +
  geom_point(
    aes(
      x = gdp_capita, 
      y = life_exp, 
      size = pop, 
      color = region
      )
    ) +
  scale_x_continuous(
    labels = scales::dollar_format(),
    breaks = scales::log_breaks(n = 10)
    ) +
  coord_trans(x = 'log10') +
  scale_size_continuous(
    labels = scales::number_format(scale = 1/1e6, suffix = "m"),
    breaks = seq(1e8,1e9, 2e8),
    range = c(1,20)
    ) +
  theme_minimal() +
  labs(
    title = "An Example of Hans Rosling's Gapminder using wbstats",
    x = "GDP per Capita (log scale)",
    y = "Life Expectancy at Birth",
    size = "Population",
    color = NULL,
    caption = "Source: World Bank"
  ) 
    
```



## Using `ggplot2` to map `wbstats` data

```{r ggplot2, fig.height=6, fig.width=8, fig.align="center", message=FALSE, warning=FALSE}
library(rnaturalearth)
library(tidyverse)
library(wbstats)

ind <- "SL.EMP.SELF.ZS"
indicator_info <- filter(wb_cachelist$indicators, indicatorID == ind)

ne_countries(returnclass = "sf") %>%
  left_join(
    wb(country = "all",
      ind
          ) %>% 
      select(-indicatorID, -indicator) %>% 
      rename(self_employed = value),
    c("iso_a3" = "iso3c")
  ) %>%
  filter(iso_a3 != "ATA") %>% # remove Antarctica
  ggplot(aes(fill = self_employed)) +
  geom_sf() +
  scale_fill_viridis_c(labels = scales::percent_format(scale = 1)) +
  theme(legend.position="bottom") +
  labs(
    title = indicator_info$indicator,
    fill = NULL,
    caption = paste("Source:", indicator_info$sourceOrg) 
  )
  
```

